### ISSUE TITLE
Remove red herring tests

### ISSUE THREAD

**Issue by marcan** [titanous/rocacheck#2]
Half the primes/lists tested are junk: the bitmasks have all bits set to one (except bit 0), which is useless and always passes (unless the RSA key has a small prime factor, but then you have bigger problems to worry about). The entries that matter are 11,13,17,19,37,53,61,71,73,79,97,103,107,109,127,151,157.

The original code seems to have been obfuscated for some reason; a more straightforward implementation of what is actually going on is here: https://gist.github.com/marcan/fc87aa78085c2b6f979aefc73fdc381f . It may make more sense to use sets/lists instead of bitmasks, depending on the programming language, and precomputing those from the generators makes it clearer what is actually going on (and only takes a few cycles on startup).

**Comment by titanous** [comment]
Thanks! Have you presented this approach upstream? I’d like to keep the implementation as close to the original as possible so that any further analysis is easy to port over.

**Comment by marcan** [comment]
I assumed there was some reason upstream was deliberately making the code more complicated, but I've filed an [issue](https://github.com/crocs-muni/roca/issues/39) about it. We'll see what they say :).

**Comment by titanous** [comment]
Great, thanks!

**Comment by marcan** [comment]
Yeah, see their latest comment. Seems it's deliberately obfuscated for no good reason.
